name: anxiety_mobile_app

description: "This is a mobile app for the collect anxiety patients data. The app collects data such as location, call logs, SMS logs, app usage, battery level, screen state, and sensor data. The collected data is then sent to a server for analysis. THIS APP IS FOR RESEARCH PURPOSES ONLY. IT IS NOT INTENDED FOR PRODUCTION USE. THE APP MAY NOT BE STABLE AND MAY CONTAIN BUGS. USE AT YOUR OWN RISK. THE DEVELOPERS ARE NOT RESPONSIBLE FOR ANY DAMAGE OR LOSS CAUSED BY THE USE OF THIS APP. BY USING THIS APP, YOU AGREE TO THE TERMS AND CONDITIONS OF THIS LICENSE. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF THIS LICENSE, DO NOT USE THIS APP. THIS APP IS PROVIDED AS IS AND WITHOUT ANY WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. THE DEVELOPERS ARE NOT LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION WITH THE APP OR THE USE OR OTHER DEALINGS IN THE APP."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.2
  geolocator: ^12.0.0
  call_log: ^4.0.0
  usage_stats: ^1.3.0
  flutter_sms_inbox: ^1.0.4
  http: ^1.2.0
  shared_preferences: ^2.3.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.0
  screen_state: ^4.0.0
  sensors_plus: ^4.0.0
  permission_handler: ^11.3.0

  battery_plus: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
